### ISSUE TITLE
USER STORY: TRIP TYPE: Wine & Dine

### ISSUE THREAD

**Issue by maliahavlicek** [maliahavlicek/go-hrvatska#12]
# DESCRIPTION
As a **foodie** I can **choose a trip based on wining and dining** so that **I can have a great time in Croatia**

# ACCEPTANCE CRITERIA

1.  Split Picture Button
2. Learn More Description
3. Criteria 3

# TASKS
- [ ] Find two pictures that complement each other about FOODs and Wines
- [ ] build split image button CSS
- [ ] Add Trip Type to JSON

# STORY POINTS
8

# EPIC Cross   #9
