### ISSUE TITLE
USER STORY: Booking: Add a Booking: model

### ISSUE THREAD

**Issue by maliahavlicek** [maliahavlicek/go-hrvatska#16]
# DESCRIPTION
As a **user** I can **add a boooking** so that **I can have a court reserved when I want it**

# ACCEPTANCE CRITERIA

1.  I can add a booking
2. I can see my bookings
3. Criteria 3

# TASKS
- [x] models.py
- [x] view for adding
- [x] list page template so you can see all available bookings
- [ ] write test to make sure validation is ok

# STORY P13, 21

# EPIC Cross References
