### ISSUE TITLE
USER STORY: FOOTER

### ISSUE THREAD

**Issue by maliahavlicek** [maliahavlicek/go-hrvatska#4]
As a **developer** I want the **footer to have links to my social networks** so that **users can get in touch with me if they want me to freelance for them**

# ACEPTANCE CRITERIA
1. Link to Linked In
2. Link to Email
3. Link to Resume Site
4. Links should be social media icons, they should rotate and enlarge upon hover and space evenly across page

# Tasks
- [ ]  Add Font Awesome
- [ ] add CSS for hover effect
- [ ] Build List in HTML

# Story Points
3 #7
