### ISSUE TITLE
USER STORY: HERO IMAGE

### ISSUE THREAD

**Issue by maliahavlicek** [maliahavlicek/go-hrvatska#5]
As a **vacation planner** I can **see beautiful images of Croatia** so that **I am tempted to book a trip**

# Acceptance Criteria
1. Have 10 iconic images from Croatia Cycle automatically
2. Images should size properly for devices
3. Have animation between images

# Tasks
- [ ] Rough in index.html
- [ ] preload images so no delay
- [ ] add javascript
- [ ] set up directory structure
- [ ] select images
- [ ] build out responsive CSS

# Story Points
3 #7
