### ISSUE TITLE
USER STORY: GET STARTED BUTTON

### ISSUE THREAD

**Issue by maliahavlicek** [maliahavlicek/go-hrvatska#6]
As a **user** I can **start booking a trip** so that **I can have a good time when I visit Croatia**

# ACCEPTANCE CRITERIA

1.  Button at top of page that takes user to next step in experience
2. Button is read with white lettering
3. Button click stops hero images from swapping out.

# TASKS
- [ ] Add Styles for Buttons
- [ ] Add Javascript for handling button click
- [ ] Hide  hero, show next step which should say "Choose your accomodations"

# STORY POINTS
3
#7
